# Use an official Python runtime as a parent image
FROM python:3.9-slim-buster

# Create a non-root user
# RUN useradd -m myuser
# USER myuser

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y

# Install the required packages
RUN pip install --no-cache-dir -r requirements.txt

# Expose port 8000 (if your application listens on this port)
EXPOSE 8000

# Run your application
CMD ["python", "api.py"]
